image: ghcr.io/cirruslabs/flutter:stable

stages:
  - test
  - build

variables:
  ANDROID_COMPILE_SDK: "34"

test:
  stage: test
  script:
    - flutter pub get
    - flutter test

build_apk:
  stage: build
  script:
    - echo "flutter.sdk=$(flutter sdk-path)" > android/local.properties
    - flutter pub get
    - flutter build apk --release --no-tree-shake-icons
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
  only:
    - main
    - master
